name: ClanCore
version: '1.0-SNAPSHOT'
main: me.skibidi.clancore.ClanCorePlugin
api-version: '1.21'
commands:
  clan:
    description: Clan main command
  team:
    description: Team main command
    usage: /clansto